name: CI/CD Pipeline

on:
  push:
    branches:
      - mainn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./rag-3
        push: true
        tags: yannicklansink/langchain-server:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set environment variables
      env:
        LANGCHAIN_TRACING_V2: ${{ secrets.LANGCHAIN_TRACING_V2 }}
        LANGCHAIN_ENDPOINT: ${{ secrets.LANGCHAIN_ENDPOINT }}
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Environment variables are set."

    - name: Delete existing Azure Container Instance
      run: |
        az container delete --resource-group langchainServer --name server-container2 --yes

    - name: Create new Azure Container Instance
      run: |
        az container create \
          --resource-group langchainServer \
          --name server-container2 \
          --image yannicklansink/langchain-server:latest \
          --restart-policy OnFailure \
          --ports 80 \
          --ip-address Public \
          --dns-name-label mylangchainserver \
          --environment-variables LANGCHAIN_TRACING_V2=${{ secrets.LANGCHAIN_TRACING_V2 }} LANGCHAIN_ENDPOINT=${{ secrets.LANGCHAIN_ENDPOINT }} LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
